/** 错误码集中处：service 与 controller/store 必须分别包装异常，禁止全局吞掉 */
export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  DOCUMENT_EMPTY: "DOCUMENT_EMPTY",
  DOCUMENT_VERSION_DUPLICATED: "DOCUMENT_VERSION_DUPLICATED",
  SECTION_PARSE_EMPTY: "SECTION_PARSE_EMPTY",
  COMPARE_SAME_DOCUMENT: "COMPARE_SAME_DOCUMENT",
  COMPARE_DOCUMENT_MISSING: "COMPARE_DOCUMENT_MISSING",
  LOCAL_STORAGE_UNAVAILABLE: "LOCAL_STORAGE_UNAVAILABLE",
  RECORD_NOT_FOUND: "RECORD_NOT_FOUND"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
