export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  EMPTY_POLICY_TEXT: "EMPTY_POLICY_TEXT",
  MISSING_VERSION_LABEL: "MISSING_VERSION_LABEL",
  DOCUMENT_NOT_FOUND: "DOCUMENT_NOT_FOUND",
  SECTION_NOT_FOUND: "SECTION_NOT_FOUND",
  DIFF_NOT_FOUND: "DIFF_NOT_FOUND",
  SAME_VERSION_COMPARE: "SAME_VERSION_COMPARE",
  REVIEWER_REQUIRED: "REVIEWER_REQUIRED",
  STORAGE_UNAVAILABLE: "STORAGE_UNAVAILABLE"
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
